In [2]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [3]:
df_1= pd.read_csv("/Users/veronicasanchez/Desktop/BOOTCAMP D.A./MODULO 4/Proyecto Pair_2/CSV/Gender Inequality Index.csv")
df_1.head()

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),GII Rank (2021),Gender Inequality Index (1990),Gender Inequality Index (1991),Gender Inequality Index (1992),Gender Inequality Index (1993),Gender Inequality Index (1994),Gender Inequality Index (1995),Gender Inequality Index (1996),Gender Inequality Index (1997),Gender Inequality Index (1998),Gender Inequality Index (1999),Gender Inequality Index (2000),Gender Inequality Index (2001),Gender Inequality Index (2002),Gender Inequality Index (2003),Gender Inequality Index (2004),Gender Inequality Index (2005),Gender Inequality Index (2006),Gender Inequality Index (2007),Gender Inequality Index (2008),Gender Inequality Index (2009),Gender Inequality Index (2010),Gender Inequality Index (2011),Gender Inequality Index (2012),Gender Inequality Index (2013),Gender Inequality Index (2014),Gender Inequality Index (2015),Gender Inequality Index (2016),Gender Inequality Index (2017),Gender Inequality Index (2018),Gender Inequality Index (2019),Gender Inequality Index (2020),Gender Inequality Index (2021)
0,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,167.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.748,0.749,0.752,0.755,0.755,0.753,0.746,0.738,0.728,0.718,0.706,0.692,0.678,0.671,0.665,0.674,0.678
1,AGO,Angola,Africa,Southern Hemisphere,Medium,SSA,148.0,136.0,0.725,0.723,0.721,0.719,0.717,0.714,0.712,0.708,0.683,0.678,0.671,0.665,0.657,0.649,0.643,0.636,0.628,0.621,0.568,0.560,0.551,0.544,0.545,0.540,0.531,0.530,0.529,0.538,0.537,0.537,0.537,0.537
2,ALB,Albania,Europe,Northern Hemisphere,High,ECA,67.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.330,0.319,0.282,0.297,0.305,0.301,0.306,0.285,0.286,0.293,0.242,0.246,0.252,0.235,0.225,0.219,0.204,0.191,0.170,0.164,0.156,0.156,0.144
3,AND,Andorra,Europe,Northern Hemisphere,Very High,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Asia,Northern Hemisphere,Very High,AS,26.0,11.0,0.659,0.647,0.640,0.632,0.635,0.627,0.624,0.616,0.609,0.605,0.605,0.602,0.599,0.597,0.592,0.584,0.311,0.202,0.193,0.185,0.175,0.181,0.171,0.161,0.151,0.126,0.118,0.112,0.103,0.056,0.050,0.049

In [4]:
df_1.shape

(195, 40)

In [5]:
df_2= pd.read_csv("/Users/veronicasanchez/Desktop/BOOTCAMP D.A./MODULO 4/Proyecto Pair_2/CSV/Dataset3.csv", sep=";")
df_2.head()

,No,Country,Level of development,European Union Membership,Currency,Women Entrepreneurship Index,Entrepreneurship Index,Inflation rate,Female Labor Force Participation Rate
0,4,Austria,Developed,Member,Euro,54.9,64.9,0.90,67.1
1,6,Belgium,Developed,Member,Euro,63.6,65.5,0.60,58.0
2,17,Estonia,Developed,Member,Euro,55.4,60.2,-0.88,68.5
3,18,Finland,Developed,Member,Euro,66.4,65.7,-0.20,67.7
4,19,France,Developed,Member,Euro,68.8,67.3,0.00,60.6

In [9]:
df_2.shape

(51, 9)

In [6]:
df_3= pd.read_csv("/Users/veronicasanchez/Desktop/BOOTCAMP D.A./MODULO 4/Proyecto Pair_2/CSV/CurrentPopulationSurvey.csv")
df_3.head()

,year,serial,numprec,hwtsupp,gq,region,statefip,metro,metarea,county,farm,month,pernum,wtsupp,relate,age,sex,race,marst,popstat,bpl,yrimmig,citizen,mbpl,fbpl,nativity,hispan,sch,educ99,schlcoll,empstat,labforce,occ,occ1990,ind1990,occ1950,ind,ind1950,classwkr,occly,occ50ly,indly,ind50ly,classwly,wkswork1,wkswork2,hrswork,uhrswork,union,incwage,incbus,incfarm,inclongj,oincwage,srcearn,ftype,quhrswor,qwkswork,qincbus,qincfarm,qinclong,qincwage,qsrcearn,o_numprec,o_hwtsupp,o_gq,o_region,o_statefip,o_metro,o_metarea,o_county,o_farm,o_month,o_pernum,o_wtsupp,o_relate,o_age,o_sex,o_race,o_marst,o_popstat,o_bpl,o_yrimmig,o_citizen,o_mbpl,o_fbpl,o_nativity,o_hispan,o_educ,o_educ99,o_schlcoll,o_empstat,o_labforce,o_occ,o_occ1990,o_ind1990,o_occ1950,o_ind,o_ind1950,o_classwkr,o_occly,o_occ50ly,o_indly,o_ind50ly,o_classwly,o_wkswork1,o_wkswork2,o_hrswork,o_uhrswork,o_union,o_incwage,o_incbus,o_incfarm,o_inclongj,o_oincwage,o_srcearn,o_ftype,o_quhrswor,o_qwkswork,o_qincbus,o_qincfarm,o_qincwage,origrace,white,black,hisp,othrace,educorig,ba,adv,groupquar,potexp,potexp2,selfemp,military,employed,annhrs,ft,niincwage,incwageman,tcoincwage,tcinclongj,tcincwage,hrwage,perconexp,expendbase10,inflate,realhrwage,uncenrealhrwage,lnrwg,hdwfcoh,notalloc,basesamp,wagesamp,occ_orig,adj_occ,occ_2010_orig,ind_orig,adj_ind,ind_2002_orig,ind_2007_orig,occ_81,ind_81,occ_2000female,unmatched_fem_81,occ_2000male,unmatched_male_81,ind_2000,occ2000_81,ind2000_81,occ_1990,ind_1990,occ_1999,ind_1999,unmatched_occ_90,occ2000_90,unmatched_ind_90,ind2000_90,indname2000_90,unmatched_occ_99,occ2000_99,unmatched_ind_99,ind2000_99,indname2000_99,un_lnrealwg,northeast,northcentral,south,west,female,adj_ind2,adj_occ2,adj_occ2name,Agriculture,miningconstruction,durables,nondurables,Transport,Utilities,Communications,retailtrade,wholesaletrade,finance,SocArtOther,hotelsrestaurants,Medical,Education,professional,publicadmin,sumadj_ind,manager,business,financialop,computer,architect,scientist,socialworker,postseceduc,legaleduc,artist,lawyerphysician,healthcare,healthsupport,protective,foodcare,building,sales,officeadmin,farmer,constructextractinstall,production,transport,sumadj_occ,LEHS
0,1990,9677,1,1052.650024,1,12,36,2.0,5607.0,NaN,1.0,3,1,1052.650024,101,58,1,3,6,1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,12.0,NaN,NaN,10,2,335,335,871.0,390,871,896,28,335,390,871,896.0,28,52,6,35.0,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1052.650024,1,12,36,2,5607,NaN,1.0,3,1,1052.650024,101,58,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,200,72,NaN,0.0,10,2,335,335,871,390,871,896,28,335,390,871,896,28,52,6,35,35,0.0,14200.0,0,0,14200.0,0.0,1.0,2,0.0,0.0,0,0,0,100,0,0,1,0,72,0,0,0,40,1600,0,0,1,1820,1,14200.0,14200.0,0.0,14200.0,14200.0,7.802198,64.639999,101.653999,1.572618,12.269874,12.269874,2.507147,1,1,1,1,335,526.0,NaN,871,837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335.0,871.0,NaN,NaN,NaN,526.0,NaN,837.0,Individual and family services,NaN,NaN,NaN,NaN,NaN,2.507147,1,0,0,0,0,62,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
1,2009,64923,4,971.200012,1,33,5,2.0,NaN,NaN,NaN,3,4,1288.880005,1260,28,1,1,6,1,9900.0,NaN,NaN,9900.0,9900.0,1.0,0.0,12.0,10.0,NaN,10,2,5120,337,762.0,310,8660,836,21,5120,310,8660,836.0,22,52,6,40.0,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0.0,0,0.0,4,971.200012,1,33,5,2,9999,0.0,NaN,3,4,1288.880005,1260,28,1,100,6,1,9900.0,0.0,0.0,9900.0,9900.0,1.0,0,73,10.0,0.0,10,2,5120,337,762,310,8660,836,21,5120,310,8660,836,22,52,6,40,40,1.0,17680.0,0,0,17680.0,0.0,1.0,5,0.0,0.0,0,0,0,100,1,0,0,0,73,0,0,0,10,100,0,0,1,2080,1,17680.0,17680.0,0.0,17680.0,17680.0,8.500000,100.063004,101.653999,1.015900,8.635149,8.635149,2.155841,0,1,1,1,5120,512.0,NaN,8660,866,NaN,8660.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.155841,0,0,1,0,0,68,42,Office and Admin Support,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1
2,1990,8425,1,1622.280029,1,12,36,3.0,5607.0,NaN,1.0,3,1,1622.280029,101,37,1,1,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,14.0,NaN,NaN,10,2,217,217,380.0,35,380,387,21,217,35,380,387.0,22,52,6,40.0,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,1622.280029,1,12,36,3,5607,NaN,1.0,3,1,1622.280029,101,37,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,100,NaN,0.0,10,2,217,217,380,35,380,387,21,217,35,380,387,22,52,6,40,40,1.0,28000.0,0,0,28000.0,0.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,100,0,0,0,17,289,0,0,1,2080,1,28000.0,28000.0,0.0,28000.0,28000.0,13.461538,64.639999,101.653999,1.572618,21.169851,21.169851,3.052578,1,1,1,1,217,154.0,NaN,380,309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217.0,380.0,NaN,NaN,NaN,154.0,NaN,309.0,Commercial and service industry machinery manu...,NaN,NaN,NaN,NaN,NaN,3.052578,1,0,0,0,0,20,21,.,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
3,1990,67963,1,2689.909912,1,42,6,3.0,7400.0,NaN,1.0,3,1,2689.909912,101,34,1,1,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,18.0,NaN,NaN,10,2,64,64,732.0,99,740,808,21,64,99,740,808.0,22,47,4,50.0,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0.0,0,0.0,1,2689.909912,1,42,6,3,7400,NaN,1.0,3,1,2689.909912,101,34,1,100,6,1,NaN,NaN,NaN,NaN,NaN,NaN,0,122,NaN,0.0,10,2,64,64,732,99,740,808,21,64,99,740,808,22,47,4,50,45,1.0,27500.0,0,0,22000.0,5500.0,1.0,2,0.0,0.0,0,0,0,100,1,0,0,0,122,0,1,0,10,100,0,0,1,2115,1,27500.0,27500.0,5500.0,22000.0,27500.0,13.002364,64.639999,101.653999,1.572618,20.447746,20.447746,3.017873,1,1,1,1,64,102.0,NaN,740,738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0,732.0,NaN,NaN,NaN,102.0,NaN,738.0,Computer systems design and related services,NaN,NaN,NaN,NaN,NaN,3.017873,0,0,0,1,0,74,20,Computer and Math Technicians,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,1981,38650,9,1911.900024,1,31,51,3.0,8840.0,NaN,1.0,3,1,1911.900024,101,38,1,4,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,13.0,NaN,NaN,10,2,245,22,791.0,290,798,849,10,153,95,539,617.0,22,52,6,80.0,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,NaN,0,NaN,9,1911.900024,1,31,51,3,8840,NaN,1.0,3,1,1911.900024,101,38,1,700,1,1,NaN,NaN,NaN,NaN,NaN,NaN,0,90,NaN,NaN,10,2,245,22,791,290,798,849,10,153,95,539,617,22,52,6,80,40,NaN,17000.0,0,0,NaN,NaN,NaN,1,NaN,NaN,0,0,0,700,0,0,0,1,90,0,0,0,19,361,0,0,1,2080,1,17000.0,17000.0,NaN,NaN,17000.0,8.173077,43.977001,101.653999,2.311526,18.892282,18.892282,2.938754,1,1,1,1,245,43.0,NaN,798,749,NaN,NaN,245.0,798.0,470.0,NaN,43.0,NaN,749.0,43.0,749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.938754,0,0,1,0,0,74,10,Managers,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1

In [10]:
df_3.shape

(344287, 234)

In [7]:
df_4= pd.read_csv("/Users/veronicasanchez/Desktop/BOOTCAMP D.A./MODULO 4/Proyecto Pair_2/CSV/PanelStudyIncomeDynamics.csv")
df_4.head()

,intnum68,pernum68,wave,sex,intnum,farminc,region,famwgt,relhead,age,employed,sch,annhrs,annlabinc,occ,ind,white,black,hisp,othrace,degree,degupd,schupd,annwks,unjob,usualhrwk,labincbus,yrsexp,yrsftexp,yrsptexp,yrsptexpsq,yrsftexpsq,yrsExpSq,yrsexpfz,yrsftexpfz,yrsptexpfz,yrsexpfzsq,yrsftexpfzsq,yrsptexpfzsq,wtrgov,selfemp,predict98,predictft98,predict00,predictft00,predict02,predictft02,predict04,predictft04,predict06,predictft06,predict08,predictft08,predict10,predictft10,origage,origannHrsHD,origannHrsWF,origannLabIncHD,origannLabIncWF,origannWeeksHD,origannWeeksWF,origcurrHrWkHD,origcurrHrWkWF,origdegreeHD,origdegreeWF,origemp,origeverwrkHD07,origeverwrkHD09,origeverwrkHD11,origeverwrkHD99,origeverwrkWF07,origeverwrkWF09,origeverwrkWF11,origeverwrkWF99,origfamWgt,origfarmInc,origindHD,origindWF,origmarSt,orignumChld,origoccHD,origoccWF,origraceHD,origraceWF,origregion,origrelHead,origsch,origschfamHD07,origschfamHD09,origschfamHD11,origschfamHD81,origschfamHD99,origschfamWF07,origschfamWF09,origschfamWF11,origschfamWF81,origschfamWF99,origsexHead,origspanHD,origspanWF,origstopwrkHDE299,origstopwrkHDE399,origstopwrkHDE499,origstopwrkHDE599,origstopwrkHDE699,origstopwrkHDU299,origstopwrkHDU399,origstopwrkHDU499,origstopwrkHDU599,origstopwrkHDU699,origstopwrkWFE299,origstopwrkWFE399,origstopwrkWFE499,origstopwrkWFE599,origstopwrkWFE699,origstopwrkWFU299,origstopwrkWFU399,origstopwrkWFU499,origstopwrkWFU599,origstopwrkWFU699,origtotYrsFTHD,origtotYrsFTWF,origtotYrsHD,origtotYrsWF,origunJobHD,origunJobWF,origwrkPriorJanHD,origwrkPriorJanWF,origwtrNewHD,origwtrNewWF,origyrNewHD,origyrNewWF,predict97,predictft97,predictfz97,predictftfz97,predictfz98,predictftfz98,predict1999,predictft1999,predictfz99,predictftfz99,predictfz00,predictftfz00,predict01,predictft01,predictfz01,predictftfz01,predictfz02,predictftfz02,predict03,predictft03,predictfz03,predictftfz03,predictfz04,predictftfz04,predictfz06,predictftfz06,predict2007,predictft2007,predictfz07,predictftfz07,predictfz08,predictftfz08,predict2009,predictft2009,predictfz09,predictftfz09,predictfz10,predictftfz10,predict2011,predictft2011,predictfz11,predictftfz11,origAdvHD,origAdvWF,origBAHD,origBAWF,origannWeeksHDE,origannWeeksHDR,origannWeeksHDU,origannWeeksWFE,origannWeeksWFR,origannWeeksWFU,origindHDE,origindWFE,origindHDU,origindWFU,origindHDR,origindWFR,origoccHDE,origoccHDR,origoccHDU,origoccWFE,origoccWFR,origoccWFU,origrace,origschHD,origschWF,origyrHghstDegHD,origyrHghstDegWF,origwtrCollDegHD,origwtrCollDegWF,origwtrCollHD,origwtrCollWF,predict,predictft,smsa,perconexp,hrwage,annhrs2,expendbase10,inflate,realhrwage,immigrantsamp,northeast,northcentral,south,west,lnrealwg,ft,potexp,potexp2,ba,adv,military,basesamp,wagesamp,female,ind2,occ2,occ2name,Agriculture,miningconstruction,durables,nondurables,Transport,Utilities,Communications,retailtrade,wholesaletrade,finance,SocArtOther,hotelsrestaurants,Medical,Education,professional,publicadmin,sumind,manager,business,financialop,computer,architect,scientist,socialworker,postseceduc,legaleduc,artist,lawyerphysician,healthcare,healthsupport,protective,foodcare,building,sales,officeadmin,farmer,constructextractinstall,production,transport,sumocc,LEHS
0,1152,24,1981,1,3505,0.0,1.0,17.000,10,34,1,16.0,1600,10000.0,492,707,1,0,0,0,1.0,1.0,17,32.000000,0,50.0,0,12.0,12.0,0.0,0.0,144.0,144.0,12.0,12.0,0.0,144.0,144.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,1600,1224,10000.0,9600.0,NaN,NaN,50,24,NaN,NaN,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.000,0.0,NaN,NaN,1,3,NaN,NaN,NaN,NaN,1,1,16,17.0,17.0,17.0,16.0,17.0,12.0,16.0,16.0,12.0,12.0,1,NaN,NaN,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7,4,7,4,5,5,NaN,NaN,5,5,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5.0,0.0,1.0,0.0,32.0,0.0,0.0,51.0,0.0,0.0,718.0,838.0,0.0,0.0,0.0,0.0,270.0,0.0,0.0,75.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1.0,43.977001,6.250000,1600.0,101.653999,2.311526,14.447040,0,1,0,0,0,2.670490,1,12.0,144.0,1,0,0,1,1,0,60,40,.,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
1,5057,171,1981,1,675,0.0,2.0,2.000,10,32,1,14.0,520,9095.0,874,357,0,1,0,0,0.0,0.0,14,13.000000,1,40.0,0,14.0,11.0,3.0,9.0,121.0,196.0,14.0,11.0,3.0,196.0,121.0,9.0,0.0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,32,520,1920,9095.0,12574.0,NaN,NaN,40,40,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000,0.0,NaN,NaN,1,3,NaN,NaN,NaN,NaN,2,1,14,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,13.0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,6,9,6,1,1,NaN,NaN,5,5,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.0,0.0,5.0,5.0,13.0,0.0,0.0,48.0,0.0,0.0,219.0,878.0,0.0,0.0,0.0,0.0,610.0,0.0,0.0,391.0,0.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1.0,43.977001,17.490385,520.0,101.653999,2.311526,40.429485,0,0,1,0,0,3.699559,1,12.0,144.0,0,0,0,1,1,0,20,60,Production,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1
2,6375,170,2009,1,8505,0.0,1.0,6.565,10,64,1,12.0,2550,45200.0,830,907,0,1,0,0,0.0,0.0,12,51.000000,0,50.0,0,39.0,38.0,1.0,1.0,1444.0,1521.0,39.0,38.0,1.0,1521.0,1444.0,1.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,2550,2550,45200.0,23000.0,51.000000,51.000000,50,50,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.565,0.0,907.0,538.0,1,2,830.0,562.0,2.0,2.0,1,10,12,12.0,12.0,12.0,12.0,12.0,14.0,14.0,14.0,12.0,14.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,17,21,17,5,5,0.0,0.0,5,5,1970.0,1985.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,5.0,5.0,1.0,0,0,1.0,100.063004,17.725491,2550.0,101.653999,1.015900,18.007324,0,1,0,0,0,2.890779,1,46.0,2116.0,0,0,0,1,1,0,62,60,Production,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1
3,2261,3,1999,1,4202,0.0,2.0,25.973,10,50,1,12.0,3072,25000.0,913,448,1,0,0,0,0.0,0.0,12,51.200001,0,60.0,0,30.0,30.0,0.0,0.0,900.0,900.0,30.0,30.0,0.0,900.0,900.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,3072,1928,25000.0,23000.0,51.200001,48.200001,60,40,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.973,0.0,NaN,NaN,1,0,NaN,NaN,1.0,1.0,2,10,12,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,1,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18,11,18,13,5,5,NaN,NaN,5,5,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,528.0,879.0,0.0,0.0,NaN,NaN,715.0,NaN,0.0,100.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,79.933998,8.138021,3072.0,101.653999,1.271724,10.349318,0,0,1,0,0,2.336920,1,32.0,1024.0,0,0,0,1,1,0,52,62,Transportation and materials moving,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1
4,5927,7,1990,1,605,0.0,3.0,14.819,10,26,1,12.0,2100,24500.0,770,157,1,0,0,0,0.0,0.0,12,50.000000,0,42.0,0,8.0,8.0,0.0,0.0,64.0,64.0,8.0,8.0,0.0,64.0,64.0,0.0,0.0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,26,2100,2016,24500.0,17000.0,NaN,NaN,42,42,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.819,0.0,NaN,NaN,4,2,NaN,NaN,1.0,1.0,3,10,12,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN,1,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,7,99,10,5,5,NaN,NaN,5,1,84.0,90.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,50.0,NaN,0.0,48.0,NaN,0.0,309.0,309.0,0.0,0.0,NaN,NaN,441.0,NaN,0.0,674.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,1,1,0.0,64.639999,11.666667,2100.0,101.653999,1.572618,18.347204,0,0,0,1,0,2.909477,1,8.0,64.0,0,0,0,1,1,0,30,60,Production,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1

In [11]:
df_4.shape

(33398, 274)

In [8]:
df_5= pd.read_csv("/Users/veronicasanchez/Desktop/BOOTCAMP D.A./MODULO 4/Proyecto Pair_2/CSV/employees.csv")
df_5.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [12]:
df_5.shape

(1000, 8)